### ISSUE TITLE
Improvements/Suggestions?

### ISSUE THREAD

**Issue by nathantannar4** [nathantannar4/TypingIndicator#1]
Anyone have any suggestions or improvements that could be made to TypingIndicator?

**Comment by lshannak** [comment]
does this work currently on MessageKit??

**Comment by nathantannar4** [comment]
@lshannak Yes. `MessageInputBar` was basically forked from this and with MessageKit 2.0 there should be no conflicts as long as as you aren't importing MessageInputBar and InputBarAccessoryView in the same file. 

Edit: Sorry was on mobile, thought this was opened in my InputBarAccessoryView repo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lshannak** [comment]
Can you tell me what version of messagekit supports this, I am using 2.0, is that sufficient?


-------- Original Message --------
Subject: Re: [nathantannar4/TypingIndicator] Improvements/Suggestions? (#1)

**Comment by lshannak** [comment]
And maybe I can make my question alot simpler, I am trying to see how this is being used, is it in the example app, I tried looking for an example in messagekit but couldnt find.

**Comment by nathantannar4** [comment]
As I said in my first response yes 2.0 is compatible. I don't stand your last question. Can you be more clear?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
As of now you would have to make a custom cell for MessageKit. If you go to the PR section in MessageKit you will see I have two methods for integrating the typing indicator. You can specify one of the branches in your podfile and then you will be able to use the indicator early

**Comment by lshannak** [comment]
Thank you for the information, I was able to get my way around it :)

**Comment by clay-mindoula** [comment]
worked very nicely

**Comment by danqing** [comment]
I have a suggestion: the pulse effect should be more consistent. Currently the bubble itself and the tails seem to animate at different intervals, which is kinda weird.
